### ISSUE TITLE
Report two bugs in using MobileSAMv2

### ISSUE THREAD

**Issue by GPIOX** [ChaoningZhang/MobileSAM#127]
Thank you for releasing MobileSAMv2. It is a useful tool in my research and saves more training time and memory

I would report two bugs in using MobileSAMv2 and I deal with these questions: 

**1. TypeError: 'type' object is not subscriptable:** 
Many codes such as scale_factor: list[float] or None = None, report TypeError. 

To do this correctly, maybe you should try: 

from typing import List, Dict, Tuple
scale_factor: List[float] or None = None

**2.  MobileSAMv2/efficientvit/models/nn/act.py:** 
21 Line: "gelu": partial(nn.GELU, approximate="tanh") report ValueError: partial object functools.partial(<class 'torch.nn.modules.activation.GELU'>, approximate='tanh') has incorrect arguments

My solution is replacing "partial(nn.GELU, approximate="tanh")" as nn.GELU

This is the first time I've used the issue feature, so I apologize for any mistakes.

**Comment by yl17104265** [comment]
The first problem may be the python version, >= 3.9

**Comment by yanzongs** [comment]
Hello, may I ask if I have the following error, how should I solve it?

Traceback (most recent call last):
  File "D:\MobileSAM\MobileSAMv2\Inference.py", line 122, in <module>
    main(args)
  File "D:\MobileSAM\MobileSAMv2\Inference.py", line 79, in main
    input_boxes1 = obj_results[0].boxes.xyxy
TypeError: 'NoneType' object is not subscriptable

**Comment by IuliaElisa** [comment]
Hi, it usually means that the model didn't predict any object on that image.

**Comment by yanzongs** [comment]
> 嗨，这通常意味着模型没有预测该图像上的任何对象，因此obj_results为空。

But I used the official photo input, why did I fail to predict the object? I also reported the same error when I used another photo input

**Comment by yanzongs** [comment]
> Hi, it usually means that the model didn't predict any object on that image, so the obj_results is empty.

But I used the official photo input, why did I fail to predict the object? I also reported the same error when I used another photo input

**Comment by moyans** [comment]
python 3.9,    same question

**Comment by yyf2002** [comment]
> > Hi, it usually means that the model didn't predict any object on that image, so the obj_results is empty.
> 
> But I used the official photo input, why did I fail to predict the object? I also reported the same error when I used another photo input

did u find the resolution for this issue? it also occurs when i try to use the official photo
