### ISSUE TITLE
mobilesamv2 bug

### ISSUE THREAD

**Issue by liujiaqi-666** [ChaoningZhang/MobileSAM#144]

**Comment by liujiaqi-666** [comment]
when I use encoder_type as tiny_vit,the results is error.
![Uploading 1.png…]()

**Comment by Pizzawookiee** [comment]
Seconded, I cannot see the image attached to this bug report for some reason but here is my own error, I believe it is the same:

Traceback (most recent call last):
  File "C:\Users\test\MobileSAM\MobileSAMv2\Inference.py", line 125, in <module>
    main(args)
  File "C:\Users\test\MobileSAM\MobileSAMv2\Inference.py", line 66, in main
    image_encoder=sam_model_registry[args.encoder_type](encoder_path[args.encoder_type])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\MobileSAM\MobileSAMv2\mobilesamv2\build_sam.py", line 115, in build_sam_vit_t_encoder
    mobile_sam.load_state_dict(state_dict['model'],strict=False)
                               ~~~~~~~~~~^^^^^^^^^
KeyError: 'model'

**Comment by misrolox** [comment]
same issue

**Comment by Shanzhaguoo** [comment]
I met the same issue; did you solve it?
