### ISSUE TITLE
convert the model to onnx

### ISSUE THREAD

**Issue by gtfaiwxm** [ChaoningZhang/MobileSAM#48]
when I convert the model to onnx, I meet the error.
Exporting onnx model to mobile_sam_onnx_opset11.onnx...
Traceback (most recent call last):
  File "/mnt/e/ncnn_project/MobileSAM/scripts/export_onnx_model.py", line 179, in <module>
    run_export(
  File "/mnt/e/ncnn_project/MobileSAM/scripts/export_onnx_model.py", line 150, in run_export
    torch.onnx.export(
  File "/home/gtf/miniconda3/envs/yolov8/lib/python3.9/site-packages/torch/onnx/__init__.py", line 275, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/gtf/miniconda3/envs/yolov8/lib/python3.9/site-packages/torch/onnx/utils.py", line 88, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/gtf/miniconda3/envs/yolov8/lib/python3.9/site-packages/torch/onnx/utils.py", line 689, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/home/gtf/miniconda3/envs/yolov8/lib/python3.9/site-packages/torch/onnx/utils.py", line 463, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/home/gtf/miniconda3/envs/yolov8/lib/python3.9/site-packages/torch/onnx/utils.py", line 200, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/gtf/miniconda3/envs/yolov8/lib/python3.9/site-packages/torch/onnx/__init__.py", line 313, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/gtf/miniconda3/envs/yolov8/lib/python3.9/site-packages/torch/onnx/utils.py", line 994, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "/home/gtf/miniconda3/envs/yolov8/lib/python3.9/site-packages/torch/onnx/symbolic_opset11.py", line 922, in repeat_interleave
    return torch.onnx.symbolic_opset9.repeat_interleave(g, self, repeats, final_dim)
  File "/home/gtf/miniconda3/envs/yolov8/lib/python3.9/site-packages/torch/onnx/symbolic_opset9.py", line 2064, in repeat_interleave
    for idx, r_split in enumerate(r_splits):
TypeError: 'torch._C.Value' object is not iterable
(Occurred when translating repeat_interleave).

**Comment by dhkim2810** [comment]
Hi @gtfaiwxm , please provide more details on your error.
- What command you used
- What environment you are on (i.e., onnx and onnxruntime)

Thank you.

**Comment by julinfn** [comment]
the same proble occurs:
command: python scripts/export_onnx_model.py --checkpoint ./weights/mobile_sam.pt --model-type vit_t --output ./mobile_sam.onnx
optset: 16 is not support ,change to 13
environment:onnx 1.14.0   onnxruntime 1.8.1

**Comment by dhkim2810** [comment]
Hi @julinfn , since we tested using `onnx==1.12.0` and `onnxruntime==1.14.0`, there could be compatibility issues.
As error suggests, please use opset 13 using `--opset 13` flag.

We will close the issue for now.
Please let us know if it still has errors.
Thank you.

**Comment by julinfn** [comment]
still has the same error. 


`Loading model...
Exporting onnx model to ./mobile_sam.onnx...
[1, 256, 64, 64] [1, 256, 64, 64]
Traceback (most recent call last):
  File "E:\git\paddle\MobileSAM\scripts\export_onnx_model.py", line 176, in <module>
    run_export(
  File "E:\git\paddle\MobileSAM\scripts\export_onnx_model.py", line 148, in run_export
    torch.onnx.export(
  File "D:\profProgram\miniconda\envs\sam\lib\site-packages\torch\onnx\__init__.py", line 316, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "D:\profProgram\miniconda\envs\sam\lib\site-packages\torch\onnx\utils.py", line 107, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "D:\profProgram\miniconda\envs\sam\lib\site-packages\torch\onnx\utils.py", line 724, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "D:\profProgram\miniconda\envs\sam\lib\site-packages\torch\onnx\utils.py", line 497, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "D:\profProgram\miniconda\envs\sam\lib\site-packages\torch\onnx\utils.py", line 216, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "D:\profProgram\miniconda\envs\sam\lib\site-packages\torch\onnx\__init__.py", line 373, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "D:\profProgram\miniconda\envs\sam\lib\site-packages\torch\onnx\utils.py", line 1032, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "D:\profProgram\miniconda\envs\sam\lib\site-packages\torch\onnx\symbolic_opset13.py", line 260, in repeat_interleave
    return torch.onnx.symbolic_opset9.repeat_interleave(g, self, repeats, final_dim)
  File "D:\profProgram\miniconda\envs\sam\lib\site-packages\torch\onnx\symbolic_opset9.py", line 2083, in repeat_interleave
    for idx, r_split in enumerate(r_splits):
TypeError: 'torch._C.Value' object is not iterable
(Occurred when translating repeat_interleave).`

**Comment by julinfn** [comment]
it's ok now，thanks

**Comment by janesunflower** [comment]
I have the same problem. torch=1.10.0+cu113, onnx==1.12.0, onnxruntime==1.14.0, opset 13

**Comment by shining-love** [comment]
> it's ok now，thanks

hello,how to solve it?

**Comment by Dai23** [comment]
在onnx==1.12.0onnxruntime==1.14.0 --opset 13 的环境下仍然存在着问题：RuntimeError: Exporting the operator repeat_interleave to ONNX opset version 13 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.
